### ISSUE TITLE
Collapse generated files

### ISSUE THREAD

**Issue by mRcfps** [tutureproject/prototype#20]
## Problem description

Some generated files, such as `package-lock.json`, should be collapsed or totally not rendered by default.

## Possible solution

For CLI, generate a new field `fold` (or something else like this):

```yaml
steps:
  - name: Step one
    commit: d8f7a0a
    explain: <YOUR EXPLANATION HERE>
    diff:
      - file: package-lock.json
        collapse: true
      - file: app.js
        explain: <YOUR EXPLANATION HERE>
```

For renderer, collapse those files by default and add a button to unfold them.
